version: '3.1'
services:
  news-server:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - news-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://news-db:5432/news
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root

  news-db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=news
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root